### ISSUE TITLE
pip install is broken with the given requirements.txt on python 3.10.8

### ISSUE THREAD

**Issue by bijookha** [aryamanarora/schwa-deletion#45]
Please update requrements.txt or specify some version. thanks for the great work though.

**Comment by debasishaimonk** [comment]
was this solved @bijookha

**Comment by bijookha** [comment]
Yes, I managed to get it working, though it still does not work out of box (checked today) but I managed. I will close this issue.

I am also working on this problem. The 95% is good but the remaining 5% cases were the troublesome cases anyway. Can you give me some advice I am trying to solve the schwa deletion problem further (for the remaining 5% also like क़ुदरती छिपकली असमान etc) for practical purpose. Can you advise me whether it is worth fine-tuning this or is it better to just rely on a comprehensive transliteration dictionary?

**Comment by bijookha** [comment]
Closing.
